config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: true
  link_dotfile_default: link
  link_on_import: nolink
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
dotfiles:
  omf_config:
    dst: ~/.config/omf
    src: omf
  fish_brew:
    dst: ~/.config/fish/conf.d/00_brew.fish
    src: fish/00_brew.fish
  omf_loader:
    dst: ~/.config/fish/conf.d/01_omf.fish
    src: fish/01_omf.fish
  fish_env_desktop:
    dst: ~/.config/fish/env.fish
    src: fish/env_desktop.fish
  fish_depot_tools:
    dst: ~/.config/fish/conf.d/10_depot_tools.fish
    src: fish/10_depot_tools.fish
  fish_krew:
    dst: ~/.config/fish/conf.d/06_krew.fish
    src: fish/06_krew.fish
  fish_cargo:
    dst: ~/.config/fish/conf.d/05_cargo.fish
    src: fish/05_cargo.fish
  fish_base16:
    dst: ~/.config/fish/conf.d/90_base16.fish
    src: fish/90_base16.fish
  i3_laptop:
    dst: ~/.config/i3/config
    src: i3/config_laptop
  i3_desktop:
    dst: ~/.config/i3/config
    src: i3/config_desktop
  i3blocks_laptop:
    dst: ~/.config/i3blocks/config
    src: i3blocks/config_laptop
  i3blocks_desktop:
    dst: ~/.config/i3blocks/config
    src: i3blocks/config_desktop
  nvim_rc:
    dst: ~/.config/nvim/init.vim
    src: nvim/init.vim
  fish_legacy:
    dst: ~/.config/fish/config.fish
    src: fish/config.fish
  termite:
    dst: ~/.config/termite/config
    src: termite/config
  rofi:
    dst: ~/.config/rofi/config
    src: rofi/config
  wallpaper:
    dst: ~/.local/share/desktop/wallpaper.png
    src: wallpaper/wallpaper.png
  tmux:
    dst: ~/.tmux.conf
    src: tmux/tmux.conf
profiles:
  lalit-xps:
    dotfiles:
    - nvim_rc
    - i3blocks_laptop
    - i3_laptop
    - termite
    - rofi
    - wallpaper
    - tmux
    - fish_cargo
    - omf_config
    - omf_loader
    - fish_base16
  lalit-hp:
    dotfiles:
    - nvim_rc
    - i3_desktop
    - i3blocks_desktop
    - fish_legacy
    - termite
    - fish_env_desktop
    - rofi
    - wallpaper
    - tmux
  lalit-do:
    dotfiles:
    - nvim_rc
  lalit-ryzen:
    dotfiles:
    - termite
    - i3_desktop
    - i3blocks_desktop
    - nvim_rc
    - rofi
    - wallpaper
    - tmux
    - fish_base16
    - fish_depot_tools
    - fish_cargo
    - omf_config
    - omf_loader
  lalitm-macbook:
    dotfiles:
    - nvim_rc
    - tmux
    - fish_depot_tools
    - fish_cargo
    - omf_config
    - omf_loader
    - fish_brew
    - fish_krew
