config:
  backup: true
  banner: true
  create: true
  dotpath: dotfiles
  ignoreempty: false
  keepdot: true
  link_dotfile_default: link
  link_on_import: nolink
  longkey: false
  showdiff: false
  workdir: ~/.config/dotdrop
dotfiles:
  omf_config:
    dst: ~/.config/omf
    src: omf
  fish_brew:
    dst: ~/.config/fish/conf.d/00_brew.fish
    src: fish/00_brew.fish
  omf_loader:
    dst: ~/.config/fish/conf.d/01_omf.fish
    src: fish/01_omf.fish
  fish_cargo:
    dst: ~/.config/fish/conf.d/05_cargo.fish
    src: fish/05_cargo.fish
  fish_krew:
    dst: ~/.config/fish/conf.d/06_krew.fish
    src: fish/06_krew.fish
  fish_depot_tools:
    dst: ~/.config/fish/conf.d/10_depot_tools.fish
    src: fish/10_depot_tools.fish
  fish_local_bin:
    dst: ~/.config/fish/conf.d/20_local_bin.fish
    src: fish/20_local_bin.fish
  fish_ssh_agent:
    dst: ~/.config/fish/conf.d/80_ssh_agent.fish
    src: fish/80_ssh_agent.fish
  fish_sway_java:
    dst: ~/.config/fish/conf.d/95_sway_java.fish
    src: fish/95_sway_java.fish
  i3_desktop:
    dst: ~/.config/i3/config
    src: i3/config_desktop
  i3blocks_laptop:
    dst: ~/.config/i3blocks/config
    src: i3blocks/config_laptop
  i3blocks_desktop:
    dst: ~/.config/i3blocks/config
    src: i3blocks/config_desktop
  nvim_rc:
    dst: ~/.config/nvim/init.vim
    src: nvim/init.vim
  termite:
    dst: ~/.config/termite/config
    src: termite/config
  rofi:
    dst: ~/.config/rofi/config.rasi
    src: rofi/config.rasi
  wallpaper:
    dst: ~/.local/share/desktop/wallpaper.png
    src: wallpaper/wallpaper.png
  tmux:
    dst: ~/.tmux.conf
    src: tmux/tmux.conf
  alacritty:
    dst: ~/.config/alacritty/alacritty.yml
    src: alacritty/alacritty.yml
  sway:
    dst: ~/.config/sway/config
    src: sway/config
profiles:
  xps-9360-arch:
    dotfiles:
    - nvim_rc
    - i3blocks_laptop
    - termite
    - rofi
    - wallpaper
    - tmux
    - fish_cargo
    - fish_local_bin
    - fish_depot_tools
    - fish_ssh_agent
    - omf_config
    - omf_loader
    - alacritty
    - sway
  arch-desktop:
    dotfiles:
    - termite
    - i3_desktop
    - i3blocks_desktop
    - nvim_rc
    - rofi
    - wallpaper
    - tmux
    - fish_depot_tools
    - fish_cargo
    - fish_ssh_agent
    - omf_config
    - omf_loader
    - alacritty
    - sway
    - fish_sway_java
  lalitm-macbook:
    dotfiles:
    - nvim_rc
    - tmux
    - fish_depot_tools
    - fish_cargo
    - omf_config
    - omf_loader
    - fish_brew
    - fish_krew
