[project]
name = ""
version = ""
description = ""
authors = [
    {name = "Lalit Maganti", email = "lalitmaganti@gmail.com"},
]
dependencies = ["docopt", "ruamel.yaml", "jinja2", "python-magic", "requests", "packaging"]
requires-python = ">=3.9"
license = {text = "MIT"}

[project.urls]
homepage = ""

[tool]
[tool.pdm]
[[tool.pdm.source]]
name = "pypi"
url = "https://pypi.org/simple"
verify_ssl = true
[tool.pdm.dev-dependencies]
dev = []

[build-system]
requires = ["pdm-pep517"]
build-backend = "pdm.pep517.api"
