#!/bin/bash
/usr/bin/rclone mount gsuite-crypt: /media/gsuite-crypt \
  --buffer-size 256M \
  --dir-cache-time 72h \
  --drive-chunk-size 32M \
  --fast-list \
  --log-level INFO \
  --log-file /home/lalit/.local/logs/rclone.log \
  --umask 002 \
  --vfs-read-chunk-size 128M \
  --vfs-read-chunk-size-limit 1G
